### ISSUE TITLE
Mostrar actividades escogidas por defecto con cada cuota

### ISSUE THREAD

**Issue by angrykoala** [softwarejimenez/WebCongresoEstudiantes#37]
hacerlo creando una tabla y marcando en apuntate las actividades por defecto

**Comment by ajimenez1503** [comment]
Otra opcion para no chocar javaScript y php. es que cuanod le des a enviar formilario, el msimo compruebe si no tienes de las actividades por defecto algunao seleciconada, ta la coja y te avise de ello.
